//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceptionClientServerApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotelrooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotelrooms()
        {
            this.Room_States = new HashSet<Room_States>();
        }
    
        public int id { get; set; }
        public Nullable<int> num { get; set; }
        public int categoryid { get; set; }
        public int reservationid { get; set; }
    
        public virtual Reservations Reservations { get; set; }
        public virtual Room_Categories Room_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room_States> Room_States { get; set; }
    }
}
