//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceptionClientServerApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_Categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room_Categories()
        {
            this.Hotelrooms = new HashSet<Hotelrooms>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> countofrooms { get; set; }
        public Nullable<decimal> pricefornight { get; set; }
        public Nullable<short> countsinglebed { get; set; }
        public Nullable<short> countdoublebed { get; set; }
        public Nullable<short> countbabybed { get; set; }
        public Nullable<short> countextrabed { get; set; }
        public Nullable<short> countwc { get; set; }
        public Nullable<int> withbathroom { get; set; }
        public Nullable<int> withshower { get; set; }
        public Nullable<int> withfridge { get; set; }
        public Nullable<int> withsofa { get; set; }
        public Nullable<int> withtv { get; set; }
        public Nullable<int> withtelephone { get; set; }
        public Nullable<int> withminibar { get; set; }
    
        public virtual Existence Existence { get; set; }
        public virtual Existence Existence1 { get; set; }
        public virtual Existence Existence2 { get; set; }
        public virtual Existence Existence3 { get; set; }
        public virtual Existence Existence4 { get; set; }
        public virtual Existence Existence5 { get; set; }
        public virtual Existence Existence6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotelrooms> Hotelrooms { get; set; }
    }
}
