//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceptionClientServerApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomStates
    {
        public int id { get; set; }
        public int hotelroomid { get; set; }
        public int staffid { get; set; }
        public int clientid { get; set; }
        public Nullable<short> countofpeople { get; set; }
        public Nullable<System.DateTime> datein { get; set; }
        public Nullable<System.DateTime> dateout { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Hotelrooms Hotelrooms { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
